### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by maronuu**
## What
Add the following items to the readme.
- How to define tasks
- Fix `Kannon` args
- Notation that `command` and `name` of a child job template are replaced.

### CODE REVIEW

**Comment by maronuu** [comment]
@kitagry @Hi-king @hirosassa 
Could you add @yokomotod as a reviewer? I don't know why but cannot do it.

**Comment by kitagry** [comment]
@maronuu I think you can invite @yokomotod to the collaborator.

**Comment by yokomotod** [comment]
@maronuu I'm now collaborator!

**Comment by yokomotod** [comment]
I haven't accepted your invitation 🙈

**Comment by yokomotod** [comment]
I think we need to give custom permission to master SA. Can you include the mention about that too?

ex.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mynamespace
  name: job-admin
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs/status"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-admin-binding
  namespace: mynamespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-admin
subjects:
  - namespace: mynamespace
    kind: ServiceAccount
    name: my-batch
```

**Comment by maronuu** [comment]
@yokomotod 
commit: 3f5358e
A section on custom permissions is added.

**Review by kitagry — APPROVED** [review]
LGTM

**Pull request merged**
